create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('computers', 'peripherals', 'accessories')),
  price numeric(10, 2) not null check (price >= 0),
  description text not null,
  features text[] not null default '{}',
  image text,
  stock integer not null default 0 check (stock >= 0),
  featured boolean not null default false,
  rating numeric(2, 1) not null default 0 check (rating >= 0 and rating <= 5),
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'products'
      and policyname = 'Products are visible to shoppers'
  ) then
    create policy "Products are visible to shoppers"
      on public.products
      for select
      using (true);
  end if;
end $$;
